apiVersion: v1 
kind: Pod 
metadata: 
 name: "myfirstpodoftheday" 
 labels: 
   app: webapp
spec: 
  containers:
    - name: "myfirstcontaineroftheday"
      image: amitkumar0441/cloudchampmonitoring_app:${IMAGE_TAG}
      ports: 
      - containerPort: 5000
---
apiVersion: v1 
kind: Service 
metadata: 
 name: "myfirstserviceoftheday"
spec: 
  selector: 
    app: webapp 
  ports:
    - protocol: TCP
      port: 5000           # Service port
      targetPort: 5000    # Container port
      nodePort: 30035  # NodePort for external access
  type: NodePort